[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/d7zysszzyjqmfbbbj4v5pj8pnzsflxkf-noctalia-shell-2025-12-04_048495b/share/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
#output_path = "/home/x/.cache/noctalia/placeholder.json"

